global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'air-purifier'

scrape_configs:
  - job_name: 'prometheus'
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
         - targets: ['localhost:8000']
